server {
    listen 80;
    server_name office.5scontrol.com;

    location = / {
        return 301 /mobile/;
    }

    location = /mobile {
        return 301 /mobile/;
    }

    location /mobile/ {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}