export const databaseTables = {
  productCategories: {
    buttonTitle: "Products",
    pageTitle: "Product Categories",
    singularName: "product category",
    path: "productCategories",
    pageDisplay: true,
    disabled: false,
  },
  products: {
    buttonTitle: "",
    pageTitle: "Products",
    singularName: "product",
    path: "products",
    pageDisplay: false,
    disabled: false,
  },
  operations: {
    buttonTitle: "Operations",
    pageTitle: "Operations",
    singularName: "operation",
    path: "operations",
    pageDisplay: true,
    disabled: false,
  },
  employees: {
    buttonTitle: "Employees",
    pageTitle: "Employees",
    singularName: "employee",
    path: "employees",
    pageDisplay: true,
    disabled: true,
  },
  equipment: {
    buttonTitle: "Equipment",
    pageTitle: "Equipment",
    singularName: "equipment",
    path: "equipment",
    pageDisplay: true,
    disabled: true,
  },
};
