name: dev-mobile

on:
  push:
    branches: [development]
    paths:
      - 'mobile/**'

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get the short Git commit hash
        id: vars
        run: |
          echo "COMMIT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ fromJson(secrets.DOCKER_CREDS).USERNAME }}
          password: ${{ fromJson(secrets.DOCKER_CREDS).PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ./mobile
          push: true\
          build-args: |
            VITE_API_BASE_URL=${{secrets.API_BASE_URL}},
            BASE_URL=${{secrets.BASE_URL}}
          tags: |
            5scontrol/5scontrol_front_mobile:latest
            5scontrol/5scontrol_front_mobile:${{ env.COMMIT_HASH }}
          cache-from: type=registry,ref=5scontrol/5scontrol_front_mobile:cache
          cache-to: type=registry,ref=5scontrol/5scontrol_front_mobile:cache,mode=max

  Deploy:
    runs-on: self-hosted
    needs: Build

    steps:
      - name: Pull the latest Docker image
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml pull 5scontrol_front_mobile

      - name: Stop the old server container
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml stop 5scontrol_front_mobile

      - name: Stop and remove the old server container
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml rm -f 5scontrol_front_mobile

      - name: Recreate and restart server container
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml up -d --no-deps 5scontrol_front_mobile
