name: dev

on:
  push:
    branches: [development]
    paths-ignore:
      - 'mobile/**'
      - '.github/workflows/dev-mobile.yml'

jobs:
  Build:
    runs-on: self-hosted-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get the short Git commit hash
        id: vars
        run: |
          echo "COMMIT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ fromJson(secrets.DOCKER_CREDS).USERNAME }}
          password: ${{ fromJson(secrets.DOCKER_CREDS).PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            5scontrol/5scontrol_front:latest
            5scontrol/5scontrol_front:${{ env.COMMIT_HASH }}
          cache-from: type=registry,ref=5scontrol/5scontrol_front:cache
          cache-to: type=registry,ref=5scontrol/5scontrol_front:cache,mode=max

  Deploy:
    runs-on: self-hosted
    needs: Build

    steps:
      - name: Pull the latest Docker image
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml pull 5scontrol_front

      - name: Stop the old server container
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml down 5scontrol_front

      - name: Recreate and restart server container
        run: sudo docker-compose -f /home/server/reps/server-/docker-compose.yml up -d --no-deps nginx 5scontrol_front
