name: dev

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [development]
    paths-ignore:
      - 'mobile/**'
      - '.github/workflows/dev-mobile.yml'

jobs:
  Build:
    runs-on: self-hosted-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get the short Git commit hash
        id: vars
        run: |
          echo "COMMIT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 5scontrol/5scontrol_front
          tags: |
            "${{ env.COMMIT_HASH }}"
            latest
        continue-on-error: false
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
        continue-on-error: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=5scontrol/5scontrol_front:cache
          cache-to: type=registry,ref=5scontrol/5scontrol_front:cache,mode=max

  Deploy:
    runs-on: self-hosted-dev
    needs: Build

    steps:
      - name: Pull the latest Docker image
        working-directory: /home/server/reps/server-
        run: |
          echo "Pulling latest Docker image for 5scontrol_front..."
          docker-compose pull 5scontrol_front

      - name: Stop and remove the old server container
        working-directory: /home/server/reps/server-
        run: |
          echo "Stopping and removing the old 5scontrol_front and nginx container..."
          docker-compose rm -fs nginx 5scontrol_front

      - name: Recreate and restart server container
        working-directory: /home/server/reps/server-
        run: |
          echo "Recreating and restarting the 5scontrol_front and nginx container..."
          docker-compose up -d --no-deps nginx 5scontrol_front
